### ISSUE TITLE
CefGlue.Demo.Avalonia run fails on Arch Linux

### ISSUE THREAD

**Issue by reimer-atb** [OutSystems/CefGlue#189]
**Steps to reproduce**

1. git clone https://github.com/OutSystems/CefGlue.git (currently on commit `769662f9aec9f8e36848dd3f5bfc314dfeda236b`)
2. cd CefGlue/CefGlue.Demo.Avalonia
3. dotnet restore && dotnet build
4. dotnet run

**Result**

CefGlue.Demo.Avalonia demo crashes at start

```
Unhandled exception. System.NotSupportedException: Can't find CEF in "/home/reimer/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/"
 ---> System.DllNotFoundException: Unable to load shared library 'libcef' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/reimer/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/runtimes/linux-x64/native/libcef.so: cannot open shared object file: No such file or directory
...
/home/reimer/Downloads/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/liblibcef: cannot open shared object file: No such file or directory

   at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash() in /home/reimer/Downloads/CefGlue/CefGlue/CefRuntime.cs:line 131
   --- End of inner exception stack trace ---
```

`CefGlue.Demo.Avalonia/bin/Debug/net8.0/runtimes/linux-x64/native/` only contains:
- `libHarfBuzzSharp.so`
- `libSkiaSharp.so`

**Expected Result**

CefGlue.Demo.Avalonia demo should start without problems

**note**

The demo starts up fine if I add the current version of CefGlue.Avalonia nuget package (`dotnet add package CefGlue.Avalonia --version 120.6099.209`), and remove the following project references:

```
  <ItemGroup>
    <ProjectReference Include="..\CefGlue.Avalonia\CefGlue.Avalonia.csproj" />
    <ProjectReference Include="..\CefGlue\CefGlue.csproj" />
    <ProjectReference Include="..\CefGlue.Common\CefGlue.Common.csproj" />
    <ProjectReference Include="..\CefGlue.Common.Shared\CefGlue.Common.Shared.csproj" />
  </ItemGroup>
```

**dotnet --info**

```
.NET SDK:
 Version:           8.0.110
 Commit:            87a66bb3d1
 Workload version:  8.0.100-manifests.6bee714d

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.110/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6bee714d
There are no installed workloads to display.

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  6.0.135 [/usr/share/dotnet/sdk]
  8.0.110 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.35 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.35 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by 00jeser** [comment]
I have the same issue when I use Rider, but when I run it using `dotnet myapp.dll`, it works. 
dotnet 8.0.108
Avalonia 11.2.0
CefGlue.Avalonia 120.6099.207
OS 6.11.5-2-cachyos

**Comment by rybcool** [comment]
KyLin v10 arm64 遇到同样的问题，求解
