### ISSUE TITLE
Problems opening a dialog which contains the CefBrowser

### ISSUE THREAD

**Issue by AlexanderDotH** [OutSystems/CefGlue#86]
I'm currently trying to replace CefNet with CefGlue. What did I do?

1. I made a Test-App to get a proper implementation of CefGlue inside a brand new Avalonia-App. 
This can be found here: https://github.com/AlexanderDotH/WebViewTest

The Test-App works fine.

2. Now I implemented it into my Main-App:
https://github.com/AlexanderDotH/OpenLyricsClient/blob/2881a90b34b7cb9a4c6ea5e71d47f6c7041fcb3d/OpenLyricsClient/External/CefNet/View/CefAuthWindow.axaml.cs#L37

Now when I try to open the Window with the exact same logic I get the following Exception:

> System.InvalidOperationException: Unable to create child window for native control host. Application manifest with supported OS list might be required.
   at Avalonia.Win32.Win32NativeControlHost.DumbWindow..ctor(Boolean layered, Nullable`1 parent) in /_/src/Windows/Avalonia.Win32/Win32NativeControlHost.cs:line 99
   at Avalonia.Win32.Win32NativeControlHost.CreateNewAttachment(Func`2 create) in /_/src/Windows/Avalonia.Win32/Win32NativeControlHost.cs:line 35
   at Avalonia.Controls.NativeControlHost.UpdateHost() in /_/src/Avalonia.Controls/NativeControlHost.cs:line 95
   at Avalonia.Controls.NativeControlHost.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/NativeControlHost.cs:line 35
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Visuals/Visual.cs:line 403
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Layout/Layoutable.cs:line 743
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Input/InputElement.cs:line 509
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 174
   at Avalonia.Visual.SetVisualParent(Visual value) in /_/src/Avalonia.Visuals/Visual.cs:line 604
   at Avalonia.Visual.SetVisualParent(IList children, Visual parent) in /_/src/Avalonia.Visuals/Visual.cs:line 642
   at Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Visuals/Visual.cs:line 622
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 687
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Xilium.CefGlue.Avalonia.Platform.AvaloniaControl.SetContent(Control content)
   at Xilium.CefGlue.Avalonia.Platform.AvaloniaControl.<InitializeRender>b__18_0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 263
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at OpenLyricsClient.Program.Main(String[] args) in C:\Users\alexander.heuschkel\RiderProjects\OpenLyricsClient\OpenLyricsClient\Program.cs:line 24

What did I do trying to fix it?

1. Opened the Window directly without the fancy backend logic. Same Issue
2. Created an entire new Window which contains the same logic as the Test-App. Same Issue
3. Checked the Program.cs which was nearly the same as the Test-App. Found nothing noticable.
4. Invoked the creation of the window to the dispatcher by using Dispatcher.UiThread.invoke. Same Issue.
5. Changed the .net version from 6.0 to 7.0 like in the Test-App. Same Issue

I actually don't know how to fix it. I reached the point where I entirely remove the webview-feature from my program.

**Comment by AlexanderDotH** [comment]
Thank you for the quick and good solution! It works now. I fully migrated to CefGlue now. Does it run on linux too?

**Comment by joaompneves** [comment]
No, Linux is not supported.
